#!/bin/bash

echo "=== LyoApp Build Fix Script ==="
echo ""

echo "PROBLEM IDENTIFIED:"
echo "=================="
echo "Critical Swift files exist on filesystem but are NOT included in the Xcode project."
echo "This causes 'Cannot find type' errors during compilation."
echo ""

echo "FILES MISSING FROM XCODE PROJECT:"
echo "================================="
echo "✅ AuthService.swift - EXISTS but not in project"
echo "✅ NetworkManager.swift - EXISTS but not in project"  
echo "✅ ErrorManager.swift - EXISTS but not in project"
echo "✅ OfflineManager.swift - EXISTS but not in project"
echo "✅ DataManager.swift - EXISTS but not in project"
echo "✅ APIServices.swift - EXISTS but not in project"
echo "✅ LearningAPIService.swift - EXISTS but not in project"
echo "✅ GamificationAPIService.swift - EXISTS but not in project"
echo "✅ AIService.swift - EXISTS but not in project"
echo "✅ EnhancedAIService.swift - EXISTS but not in project"
echo ""

echo "SOLUTION STEPS:"
echo "=============="
echo "1. Open Xcode"
echo "2. Open the LyoApp.xcodeproj file"
echo "3. In the Project Navigator, right-click on 'Core/Services' group"
echo "4. Choose 'Add Files to \"LyoApp\"'"
echo "5. Navigate to and add these files:"
echo "   - LyoApp/Core/Services/AuthService.swift"
echo "   - LyoApp/Core/Network/NetworkManager.swift"
echo "   - LyoApp/Core/Services/ErrorManager.swift"
echo "   - LyoApp/Core/Services/OfflineManager.swift"
echo "   - LyoApp/Core/Services/DataManager.swift"
echo "   - LyoApp/Core/Services/APIServices.swift"
echo "   - LyoApp/Core/Services/LearningAPIService.swift"
echo "   - LyoApp/Core/Services/GamificationAPIService.swift"
echo "   - LyoApp/Core/Services/AIService.swift"
echo "   - LyoApp/Core/Services/EnhancedAIService.swift"
echo "6. Make sure 'Add to target: LyoApp' is checked"
echo "7. Click 'Add'"
echo ""

echo "VERIFICATION:"
echo "============"
echo "After adding the files, try building again:"
echo "Product → Build (⌘+B)"
echo ""

echo "If you prefer command line, here are the exact file paths to add:"
find LyoApp -name "AuthService.swift" -o -name "NetworkManager.swift" -o -name "ErrorManager.swift" -o -name "OfflineManager.swift" -o -name "DataManager.swift" -o -name "APIServices.swift" -o -name "LearningAPIService.swift" -o -name "GamificationAPIService.swift" -o -name "AIService.swift" -o -name "EnhancedAIService.swift"
