name: LyoApp
options:
  bundleIdPrefix: com.lyo
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
settings:
  DEVELOPMENT_TEAM: ""
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  LyoApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: LyoApp
        excludes:
          - "**/*.md"
    resources:
      - path: LyoApp/Resources
        optional: true
    info:
      path: LyoApp/Resources/Info.plist
      properties:
        CFBundleDisplayName: LyoApp
        CFBundleIdentifier: com.lyo.lyoapp
        CFBundleName: LyoApp
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "LyoApp uses your microphone to enable voice interaction with the AI study assistant. You can ask questions and receive spoken responses to enhance your learning experience."
        NSSpeechRecognitionUsageDescription: "LyoApp uses speech recognition to convert your voice into text so the AI study assistant can understand and respond to your questions. This helps provide hands-free learning assistance."
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lyo.lyoapp
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1,2"
schemes:
  LyoApp:
    build:
      targets:
        LyoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release